spring:
  application:
    name: SpringSecurityProject
  security:
    user:
      name: user
      password: user
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql
      data-locations: classpath:/data.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/security_db
    initialization-mode: never
    username: postgres
    password: 3478
logging:
  level:
    org.springframework.security: trace